class Part:
    def __init__(self):
        self.trader_id = 16
        self.description = None               #########
        self.manufacturer_part_number = None  #########
        self.brand_name = None                #########
        self.address = '[{"address":"Acura Almulla, Car Dealer Rd, Kuwait","location":"https://maps.app.goo.gl/J3oPuFs33svZGpK89"}]'
        self.products_img = None              #########
        self.madeIn = None 
        self.price = None                     #########
        self.is_offer = 0
        self.offer_price = 0 
        self.offer_start_date = None 
        self.offer_end_date = None 
        self.rating = 0
        self.review_count = 0
        self.type = None                      #########
        self.is_best_seller = 0
        self.is_mobilawy = 0
        self.assembly_kit = 1
        self.product_line = None 
        self.frontOrRear = None 
        self.tyre_speed_rate = None 
        self.maximum_tyre_load = None
        self.tyre_engraving = None 
        self.rim_diameter = None 
        self.tyre_height = None 
        self.tyre_width = None
        self.kilometer = 0
        self.oil_type = None 
        self.battery_replacement_available = 0
        self.volt = None
        self.ampere = None 
        self.liter = 0
        self.color = None 
        self.Number_spark_pulgs = None 
        self.created_at = '14/08/2024'
        self.businessCategories_id = 1
        self.enabled = 1
        self.products_name = None             #########
        self.warranty = None
        self.disabled_at = None 
        self.updated_at = None 
        self.status = "Accepted"
        self.qtyInStock = 500
        self.deletedAt = None
        self.Brand = None                     #########
        self.Year = None                      #########
        self.Model = None                     #########
        self.first_img_src = None             #########